"""Add DailyMarket model 9/11/2024

Revision ID: 1c916c34b80e
Revises: c00205252157
Create Date: 2024-09-11 15:40:07.142782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c916c34b80e'
down_revision: Union[str, None] = 'c00205252157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
