"""Add MajorHolder table allow null 2

Revision ID: 64ac0ed3aa47
Revises: 7f8f410ffe10
Create Date: 2024-09-10 17:29:18.559092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ac0ed3aa47'
down_revision: Union[str, None] = '7f8f410ffe10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_holder', 'reported',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_holder', 'reported',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
