"""add market

Revision ID: 6d8941c557b8
Revises: 5bd07dae36bb
Create Date: 2024-08-29 21:21:05.018911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d8941c557b8"
down_revision: Union[str, None] = "5bd07dae36bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("average", sa.Float(), nullable=True),
        sa.Column("price_previous_close", sa.Float(), nullable=True),
        sa.Column("price_basic", sa.Float(), nullable=True),
        sa.Column("total_volume", sa.Float(), nullable=True),
        sa.Column("deal_volume", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("putthrough_volume", sa.Float(), nullable=True),
        sa.Column("total_trade", sa.Float(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("putthrough_value", sa.Float(), nullable=True),
        sa.Column("buy_foreign_quantity", sa.Float(), nullable=True),
        sa.Column("buy_foreign_value", sa.Float(), nullable=True),
        sa.Column("sell_foreign_quantity", sa.Float(), nullable=True),
        sa.Column("sell_foreign_value", sa.Float(), nullable=True),
        sa.Column("buy_count", sa.Float(), nullable=True),
        sa.Column("buy_quantity", sa.Float(), nullable=True),
        sa.Column("sell_count", sa.Float(), nullable=True),
        sa.Column("sell_quantity", sa.Float(), nullable=True),
        sa.Column("buy_avg", sa.Float(), nullable=True),
        sa.Column("sell_avg", sa.Float(), nullable=True),
        sa.Column("adj_ratio", sa.Float(), nullable=True),
        sa.Column("adj_close", sa.Float(), nullable=True),
        sa.Column("adj_open", sa.Float(), nullable=True),
        sa.Column("adj_high", sa.Float(), nullable=True),
        sa.Column("adj_low", sa.Float(), nullable=True),
        sa.Column("current_foreign_room", sa.Float(), nullable=True),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("shares_out_standing", sa.Float(), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("market_capitalization", sa.Float(), nullable=True),
        sa.Column("free_shares", sa.Float(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol_ticker", "date", name="uix_symbol_date"),
    )
    op.add_column("symbol", sa.Column("short_industry", sa.String(), nullable=True))
    op.add_column("symbol", sa.Column("cap_ratio", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("symbol", "cap_ratio")
    op.drop_column("symbol", "short_industry")
    op.drop_table("market")
    # ### end Alembic commands ###
