"""Add UpdateQuote model

Revision ID: 74d95621f475
Revises: 6d8941c557b8
Create Date: 2024-09-10 10:28:33.309134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d95621f475'
down_revision: Union[str, None] = '6d8941c557b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('symbol_ticker', sa.String(length=15), nullable=False),
    sa.Column('price_current', sa.Float(), nullable=True),
    sa.Column('price_last', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('price_open', sa.Float(), nullable=True),
    sa.Column('price_close', sa.Float(), nullable=True),
    sa.Column('price_average', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('price_bid1', sa.Float(), nullable=True),
    sa.Column('quantity_bid1', sa.Float(), nullable=True),
    sa.Column('price_bid2', sa.Float(), nullable=True),
    sa.Column('quantity_bid2', sa.Float(), nullable=True),
    sa.Column('price_bid3', sa.Float(), nullable=True),
    sa.Column('quantity_bid3', sa.Float(), nullable=True),
    sa.Column('price_ask1', sa.Float(), nullable=True),
    sa.Column('quantity_ask1', sa.Float(), nullable=True),
    sa.Column('price_ask2', sa.Float(), nullable=True),
    sa.Column('quantity_ask2', sa.Float(), nullable=True),
    sa.Column('price_ask3', sa.Float(), nullable=True),
    sa.Column('quantity_ask3', sa.Float(), nullable=True),
    sa.Column('buy_foreign_value', sa.Float(), nullable=True),
    sa.Column('sell_foreign_value', sa.Float(), nullable=True),
    sa.Column('buy_foreign_quantity', sa.Float(), nullable=True),
    sa.Column('current_foreign_room', sa.Float(), nullable=True),
    sa.Column('total_active_buy_volume', sa.Float(), nullable=True),
    sa.Column('total_active_sell_volume', sa.Float(), nullable=True),
    sa.Column('price_percent_change', sa.Float(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_ticker'], ['symbol.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_quote')
    # ### end Alembic commands ###
