"""Add MajorHolder table allow null

Revision ID: 7f8f410ffe10
Revises: f1ed23de901f
Create Date: 2024-09-10 17:18:51.944843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8f410ffe10'
down_revision: Union[str, None] = 'f1ed23de901f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_holder', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('major_holder', 'position',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('major_holder', 'shares',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('major_holder', 'ownership',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('major_holder', 'is_organization',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('major_holder', 'is_foreigner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('major_holder', 'is_foundation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('major_holder', 'is_listing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_holder', 'is_listing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('major_holder', 'is_foundation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('major_holder', 'is_foreigner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('major_holder', 'is_organization',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('major_holder', 'ownership',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('major_holder', 'shares',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('major_holder', 'position',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('major_holder', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
