"""change update quote

Revision ID: 8f8c534cf2b4
Revises: 6c446180ea07
Create Date: 2024-10-24 15:03:47.001766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8c534cf2b4'
down_revision: Union[str, None] = '6c446180ea07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_update_quote_symbol_date2', 'update_quote', ['symbol_ticker', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_update_quote_symbol_date2', 'update_quote', type_='unique')
    # ### end Alembic commands ###
