"""during session

Revision ID: b75ed81c100f
Revises: d22e498d9eb6
Create Date: 2024-11-11 15:45:40.858092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b75ed81c100f"
down_revision: Union[str, None] = "d22e498d9eb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_quote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("side", sa.String(length=3), nullable=True),
        sa.Column("match_price", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("total_volume", sa.Float(), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_ticker", "datetime", name="uq_update_quote_symbol_datetime"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_quote")
    # ### end Alembic commands ###
