"""Change update quote date to datetime with timezone

Revision ID: c00205252157
Revises: 64ac0ed3aa47
Create Date: 2024-09-11 09:02:19.466043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c00205252157"
down_revision: Union[str, None] = "64ac0ed3aa47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "update_quote", sa.Column("datetime", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("update_quote", "date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("update_quote", "date", existing_type=sa.DATE(), nullable=False)
    op.drop_column("update_quote", "datetime")
    # ### end Alembic commands ###
