"""Add historyData model 9/11/2024

Revision ID: cae629a365cf
Revises: 583e4c55601c
Create Date: 2024-09-11 17:55:00.540751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cae629a365cf"
down_revision: Union[str, None] = "583e4c55601c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history_data_processing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("percent_change", sa.Float(), nullable=True),
        sa.Column("max_bull_20", sa.Integer(), nullable=True),
        sa.Column("max_bear_20", sa.Integer(), nullable=True),
        sa.Column("max_bull_50", sa.Integer(), nullable=True),
        sa.Column("max_bear_50", sa.Integer(), nullable=True),
        sa.Column("current_position", sa.Integer(), nullable=True),
        sa.Column("median_bull_20", sa.Float(), nullable=True),
        sa.Column("median_bear_20", sa.Float(), nullable=True),
        sa.Column("median_bull_50", sa.Float(), nullable=True),
        sa.Column("median_bear_50", sa.Float(), nullable=True),
        sa.Column("range_demand_support_20", sa.Float(), nullable=True),
        sa.Column("range_demand_support_50", sa.Float(), nullable=True),
        sa.Column("range_current_support_20", sa.Float(), nullable=True),
        sa.Column("range_current_support_50", sa.Float(), nullable=True),
        sa.Column("range_demand_current_20", sa.Float(), nullable=True),
        sa.Column("range_demand_current_50", sa.Float(), nullable=True),
        sa.Column("range_current_lastweek_5", sa.Float(), nullable=True),
        sa.Column("range_current_lastmonth_20", sa.Float(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_ticker", "date", name="uq_history_data_processing_symbol_date"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("history_data_processing")
    # ### end Alembic commands ###
