"""history data

Revision ID: d05663267564
Revises: b75ed81c100f
Create Date: 2024-11-13 17:26:02.058704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05663267564'
down_revision: Union[str, None] = 'b75ed81c100f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_ticker', sa.String(length=15), nullable=False),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('price_open', sa.Float(), nullable=True),
    sa.Column('price_average', sa.Float(), nullable=True),
    sa.Column('price_close', sa.Float(), nullable=True),
    sa.Column('price_basic', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('deal_volume', sa.Float(), nullable=True),
    sa.Column('putthrough_volume', sa.Float(), nullable=True),
    sa.Column('total_value', sa.BigInteger(), nullable=True),
    sa.Column('putthrough_value', sa.BigInteger(), nullable=True),
    sa.Column('buy_foreign_quantity', sa.BigInteger(), nullable=True),
    sa.Column('buy_foreign_value', sa.BigInteger(), nullable=True),
    sa.Column('sell_foreign_quantity', sa.BigInteger(), nullable=True),
    sa.Column('sell_foreign_value', sa.BigInteger(), nullable=True),
    sa.Column('buy_count', sa.BigInteger(), nullable=True),
    sa.Column('buy_quantity', sa.BigInteger(), nullable=True),
    sa.Column('sell_count', sa.BigInteger(), nullable=True),
    sa.Column('sell_quantity', sa.BigInteger(), nullable=True),
    sa.Column('adj_ratio', sa.Float(), nullable=True),
    sa.Column('current_foreign_room', sa.Float(), nullable=True),
    sa.Column('prop_trading_net_deal_value', sa.BigInteger(), nullable=True),
    sa.Column('prop_trading_net_pt_value', sa.BigInteger(), nullable=True),
    sa.Column('prop_trading_net_value', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_ticker'], ['symbol.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_ticker', 'date', name='uq_update_quote_symbol_datetime4')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_price')
    # ### end Alembic commands ###
