"""Add Post, PostGroup, PostSource, and TaggedSymbol models

Revision ID: df71c5e0ed11
Revises: cae629a365cf
Create Date: 2024-10-02 11:05:33.238047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df71c5e0ed11"
down_revision: Union[str, None] = "cae629a365cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_groups",
        sa.Column("post_group_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fireant_post_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("post_group_id"),
        sa.UniqueConstraint("fireant_post_group_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "post_sources",
        sa.Column("post_source_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fireant_post_source_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("post_source_id"),
        sa.UniqueConstraint("fireant_post_source_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fireant_post_id", sa.Integer(), nullable=False),
        sa.Column("post_group_id", sa.Integer(), nullable=True),
        sa.Column("post_source_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_source_content_full", sa.Boolean(), nullable=True),
        sa.Column("post_source_url", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("original_content", sa.String(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("has_image", sa.Boolean(), nullable=True),
        sa.Column("has_file", sa.Boolean(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("link_image", sa.String(), nullable=True),
        sa.Column("link_title", sa.String(), nullable=True),
        sa.Column("link_description", sa.String(), nullable=True),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("is_top", sa.Boolean(), nullable=True),
        sa.Column("is_expert_idea", sa.Boolean(), nullable=True),
        sa.Column("liked", sa.Boolean(), nullable=True),
        sa.Column("total_likes", sa.Integer(), nullable=True),
        sa.Column("total_replies", sa.Integer(), nullable=True),
        sa.Column("total_shares", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_group_id"],
            ["post_groups.post_group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_source_id"],
            ["post_sources.post_source_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
        sa.UniqueConstraint("fireant_post_id"),
    )
    op.create_table(
        "tagged_symbols",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tagged_symbols")
    op.drop_table("posts")
    op.drop_table("post_sources")
    op.drop_table("post_groups")
    # ### end Alembic commands ###
