"""Create market metion table

Revision ID: f12c65428b16
Revises: 748850837b66
Create Date: 2024-10-16 17:58:43.346855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f12c65428b16"
down_revision: Union[str, None] = "748850837b66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_mentions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("day_color", sa.String(), nullable=True),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.Column("week_color", sa.String(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("month_color", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_ticker", "date", name="uix_symbol_date_market_metion"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_mentions")
    # ### end Alembic commands ###
