"""Add MajorHolder table

Revision ID: f1ed23de901f
Revises: c5faf28bbaa0
Create Date: 2024-09-10 16:44:41.020045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1ed23de901f"
down_revision: Union[str, None] = "c5faf28bbaa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "major_holder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.String(length=255), nullable=False),
        sa.Column("shares", sa.Float(), nullable=False),
        sa.Column("ownership", sa.Float(), nullable=False),
        sa.Column("is_organization", sa.Boolean(), nullable=False),
        sa.Column("is_foreigner", sa.Boolean(), nullable=False),
        sa.Column("is_foundation", sa.Boolean(), nullable=False),
        sa.Column("is_listing", sa.Boolean(), nullable=False),
        sa.Column("listing_symbol", sa.String(length=10), nullable=True),
        sa.Column("reported", sa.Date(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("major_holder")
    # ### end Alembic commands ###
