"""Add UpdateQuote table 3

Revision ID: f64cb6773de5
Revises: fc5a524c45ba
Create Date: 2024-09-10 14:27:02.269047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64cb6773de5'
down_revision: Union[str, None] = 'fc5a524c45ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
