"""Add DailyMarket model add funtion 9/11/2024

Revision ID: 583e4c55601c
Revises: c00205252157
Create Date: 2024-09-11 16:05:55.372975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "583e4c55601c"
down_revision: Union[str, None] = "c00205252157"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_market",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("price_percent_change", sa.Float(), nullable=True),
        sa.Column("price_change", sa.Float(), nullable=True),
        sa.Column("total_active_buy_volume", sa.Float(), nullable=True),
        sa.Column("total_active_sell_volume", sa.Float(), nullable=True),
        sa.Column("buy_foreign_quantity", sa.Float(), nullable=True),
        sa.Column("buy_foreign_value", sa.Float(), nullable=True),
        sa.Column("sell_foreign_quantity", sa.Float(), nullable=True),
        sa.Column("sell_foreign_value", sa.Float(), nullable=True),
        sa.Column("current_foreign_room", sa.Float(), nullable=True),
        sa.Column("total_volume", sa.Float(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_ticker", "date", name="uq_update_quote_symbol_date"
        ),
    )
    op.add_column(
        "update_quote", sa.Column("sell_foreign_quantity", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("update_quote", "sell_foreign_quantity")
    op.drop_table("daily_market")
    # ### end Alembic commands ###
