"""init db

Revision ID: 5bd07dae36bb
Revises: 
Create Date: 2024-08-09 14:27:13.193069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bd07dae36bb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "symbol",
        sa.Column("ticker", sa.String(length=15), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "finance_report",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("lever", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.CheckConstraint("type IN (1, 2, 3)", name="check_report_type"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["finance_report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "symbol_ticker", name="unique_report_name"),
    )
    op.create_table(
        "data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.CheckConstraint("quarter IN (0, 1, 2, 3, 4)", name="check_quarter"),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["finance_report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_id", "quarter", "year", name="unique_report_quarter_year"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data")
    op.drop_table("finance_report")
    op.drop_table("symbol")
    # ### end Alembic commands ###
