"""Create Subsidiaries table

Revision ID: 6c446180ea07
Revises: f12c65428b16
Create Date: 2024-10-18 09:06:51.992653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c446180ea07"
down_revision: Union[str, None] = "f12c65428b16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subsidiaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=True),
        sa.Column("sub_symbol", sa.String(length=15), nullable=True),
        sa.Column("exchange", sa.String(length=50), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("international_name", sa.String(length=255), nullable=True),
        sa.Column("company_profile", sa.String(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=True),
        sa.Column("ownership", sa.Float(), nullable=True),
        sa.Column("shares", sa.BigInteger(), nullable=True),
        sa.Column("is_listed", sa.Boolean(), nullable=True),
        sa.Column("charter_capital", sa.BigInteger(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subsidiaries")
    # ### end Alembic commands ###
