"""Create financial_scores table

Revision ID: 748850837b66
Revises: df71c5e0ed11
Create Date: 2024-10-16 15:52:49.045391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "748850837b66"
down_revision: Union[str, None] = "df71c5e0ed11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "score",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol_ticker", sa.String(length=15), nullable=False),
        sa.Column("roas_score", sa.Integer(), nullable=True),
        sa.Column("cfo_score", sa.Integer(), nullable=True),
        sa.Column("delta_roas_score", sa.Integer(), nullable=True),
        sa.Column("accrual_score", sa.Integer(), nullable=True),
        sa.Column("delta_lever_score", sa.Integer(), nullable=True),
        sa.Column("delta_liquid_score", sa.Integer(), nullable=True),
        sa.Column("eq_offer_score", sa.Integer(), nullable=True),
        sa.Column("delta_margin_score", sa.Integer(), nullable=True),
        sa.Column("delta_turn_score", sa.Integer(), nullable=True),
        sa.Column("piotroski_f_score", sa.Integer(), nullable=True),
        sa.Column("manufacturing_z_score", sa.Float(), nullable=True),
        sa.Column("non_manufacturing_z_score", sa.Float(), nullable=True),
        sa.Column("manufacturing_status", sa.String(), nullable=True),
        sa.Column("non_manufacturing_status", sa.String(), nullable=True),
        sa.Column("manufacturing_sp_rating", sa.String(), nullable=True),
        sa.Column("non_manufacturing_sp_rating", sa.String(), nullable=True),
        sa.Column("manufacturing_moody_rating", sa.String(), nullable=True),
        sa.Column("non_manufacturing_moody_rating", sa.String(), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("company_type", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol_ticker"],
            ["symbol.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_ticker", "quarter", "year", name="unique_score_quarter_year"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("score")
    # ### end Alembic commands ###
