"""add buy/sell count in update_quote

Revision ID: d22e498d9eb6
Revises: 8f8c534cf2b4
Create Date: 2024-11-11 13:05:31.892177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d22e498d9eb6"
down_revision: Union[str, None] = "8f8c534cf2b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("update_quote", sa.Column("buy_count", sa.Float(), nullable=True))
    op.add_column("update_quote", sa.Column("sell_count", sa.Float(), nullable=True))
    op.add_column("update_quote", sa.Column("buy_quantity", sa.Float(), nullable=True))
    op.add_column("update_quote", sa.Column("sell_quantity", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("update_quote", "sell_quantity")
    op.drop_column("update_quote", "buy_quantity")
    op.drop_column("update_quote", "sell_count")
    op.drop_column("update_quote", "buy_count")
    # ### end Alembic commands ###
