CREATE OR REPLACE FUNCTION update_quote(
    p_symbol VARCHAR,
    p_date DATE,
    p_price_current NUMERIC,
    p_price_last NUMERIC,
    p_price_high NUMERIC,
    p_price_low NUMERIC,
    p_price_open NUMERIC,
    p_price_close NUMERIC,
    p_price_average NUMERIC,
    p_total_volume NUMERIC,
    p_volume NUMERIC,
    p_total_value NUMERIC,
    p_price_bid1 NUMERIC,
    p_quantity_bid1 NUMERIC,
    p_price_bid2 NUMERIC,
    p_quantity_bid2 NUMERIC,
    p_price_bid3 NUMERIC,
    p_quantity_bid3 NUMERIC,
    p_price_ask1 NUMERIC,
    p_quantity_ask1 NUMERIC,
    p_price_ask2 NUMERIC,
    p_quantity_ask2 NUMERIC,
    p_price_ask3 NUMERIC,
    p_quantity_ask3 NUMERIC,
    p_buy_foreign_value NUMERIC,
    p_sell_foreign_value NUMERIC,
    p_buy_foreign_quantity NUMERIC,
    p_current_foreign_room NUMERIC,
    p_total_active_buy_volume NUMERIC,
    p_total_active_sell_volume NUMERIC,
    p_price_percent_change NUMERIC,
    p_price_change NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO update_quote (
        symbol_ticker, date, price_current, price_last, price_high, price_low,
        price_open, price_close, price_average, total_volume, volume, total_value,
        price_bid1, quantity_bid1, price_bid2, quantity_bid2, price_bid3, quantity_bid3,
        price_ask1, quantity_ask1, price_ask2, quantity_ask2, price_ask3, quantity_ask3,
        buy_foreign_value, sell_foreign_value, buy_foreign_quantity, current_foreign_room,
        total_active_buy_volume, total_active_sell_volume, price_percent_change, price_change
    )
    VALUES (
        p_symbol, p_date, p_price_current, p_price_last, p_price_high, p_price_low,
        p_price_open, p_price_close, p_price_average, p_total_volume, p_volume, p_total_value,
        p_price_bid1, p_quantity_bid1, p_price_bid2, p_quantity_bid2, p_price_bid3, p_quantity_bid3,
        p_price_ask1, p_quantity_ask1, p_price_ask2, p_quantity_ask2, p_price_ask3, p_quantity_ask3,
        p_buy_foreign_value, p_sell_foreign_value, p_buy_foreign_quantity, p_current_foreign_room,
        p_total_active_buy_volume, p_total_active_sell_volume, p_price_percent_change, p_price_change
    )
    ON CONFLICT (symbol_ticker) DO UPDATE
    SET
        date = EXCLUDED.date,
        price_current = EXCLUDED.price_current,
        price_last = EXCLUDED.price_last,
        price_high = EXCLUDED.price_high,
        price_low = EXCLUDED.price_low,
        price_open = EXCLUDED.price_open,
        price_close = EXCLUDED.price_close,
        price_average = EXCLUDED.price_average,
        total_volume = EXCLUDED.total_volume,
        volume = EXCLUDED.volume,
        total_value = EXCLUDED.total_value,
        price_bid1 = EXCLUDED.price_bid1,
        quantity_bid1 = EXCLUDED.quantity_bid1,
        price_bid2 = EXCLUDED.price_bid2,
        quantity_bid2 = EXCLUDED.quantity_bid2,
        price_bid3 = EXCLUDED.price_bid3,
        quantity_bid3 = EXCLUDED.quantity_bid3,
        price_ask1 = EXCLUDED.price_ask1,
        quantity_ask1 = EXCLUDED.quantity_ask1,
        price_ask2 = EXCLUDED.price_ask2,
        quantity_ask2 = EXCLUDED.quantity_ask2,
        price_ask3 = EXCLUDED.price_ask3,
        quantity_ask3 = EXCLUDED.quantity_ask3,
        buy_foreign_value = EXCLUDED.buy_foreign_value,
        sell_foreign_value = EXCLUDED.sell_foreign_value,
        buy_foreign_quantity = EXCLUDED.buy_foreign_quantity,
        current_foreign_room = EXCLUDED.current_foreign_room,
        total_active_buy_volume = EXCLUDED.total_active_buy_volume,
        total_active_sell_volume = EXCLUDED.total_active_sell_volume,
        price_percent_change = EXCLUDED.price_percent_change,
        price_change = EXCLUDED.price_change;
END;
$$ LANGUAGE plpgsql;